name: Nekonyatsu-ネコポイ

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y bc bison flex libssl-dev make gcc clang curl git wget zip python3

    - name: Clone Proton-Clang
      run: |
        git clone --depth=1 https://github.com/kdrag0n/proton-clang.git ~/clang

    - name: Build Kernel
      run: |
        export PATH=~/clang/bin:$PATH
        export ARCH=arm64
        export SUBARCH=arm64
        make O=out ARCH=arm64 vendor/fog-perf_defconfig
        make -j$(nproc) O=out ARCH=arm64 CC=clang

    - name: Create flashable zip with AnyKernel3
      run: |
        git clone --depth=1 https://github.com/osm0sis/AnyKernel3.git
        cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3/
        cd AnyKernel3
        zip -r9 ../Kernel-Nekonyatsu.zip *

    - name: Upload zip
      uses: actions/upload-artifact@v4
      with:
        name: Kernel-Nekonyatsu
        path: Kernel-Nekonyatsu.zip
